### ISSUE TITLE
something wrong with resampling uv map

### ISSUE THREAD

**Issue by willie1997** [zengwang430521/DecoMR#1]
Given smpl shape and pose parameters, I used get_UV_map(verts) and directly resampled the UV map generated from that function. The result is like this: 
![image](https://user-images.githubusercontent.com/39046939/88504537-a6cca780-d007-11ea-9ce9-00cd9306cf64.png)
![image](https://user-images.githubusercontent.com/39046939/88504751-222e5900-d008-11ea-873f-5d2b39a9aaa2.png)
I have tried 'SMPL' and 'BF'. How to fix this problem and obtain a smooth mesh?

**Comment by zengwang430521** [comment]
Could you please provide your test codes? I have tested as you describe and got smooth mesh. 

![image](https://user-images.githubusercontent.com/28900607/88540814-3db85480-d046-11ea-8777-a7ae110ba6fb.png)

**Comment by willie1997** [comment]
The code is quite simple:
    ```
uv_gen = Index_UV_Generator(128, -1, 'BF')
    verts, face = read_obj('./v_template.obj')
    verts = torch.from_numpy(verts).float()
    uv = uv_gen.get_UV_map(verts)
    mesh = uv_gen.resample(uv)[0].numpy()
    write_obj('out.obj', mesh, face)
```
v_template.obj is just the template mesh of smpl.
![image](https://user-images.githubusercontent.com/39046939/88550230-e6b97c00-d053-11ea-8294-59b922bde4ff.png)

**Comment by willie1997** [comment]
The code is quite simple:
‘’‘
uv_gen = Index_UV_Generator(128, -1, 'BF')
verts, face = read_obj('./v_template.obj')
verts = torch.from_numpy(verts).float()
uv = uv_gen.get_UV_map(verts)
mesh = uv_gen.resample(uv)[0].numpy()
write_obj('out.obj', mesh, face)
’‘’
v_template.obj is just the template mesh of smpl.
![image](https://user-images.githubusercontent.com/39046939/88550453-35ffac80-d054-11ea-8958-7c9d340d0e23.png)

**Comment by zengwang430521** [comment]
OK，this phenomenon  is caused by the drawback of our UV map generator.
To make sure that the bilinear sampling work well, there is a one-pixel-dilation process in the function _**get_UV_map**_. And when the resolution of UV map is not high enough, such dilation may lead to the overlap on the UV map, which causes the wrong vertices on the reconstructed mesh. 
To solve this problem, one solution is to use higher UV map resolution, such as 256. In our work, we only use 128 as the final resolution to reduce the computational complexity and the result is acceptable.
