### ISSUE TITLE
dp_loss weight meaning?

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#20]
May I ask what is the meaning of the weight in line 276-280 
in https://github.com/zengwang430521/DecoMR/blob/master/train/base_trainer.py#L276?

Is this weighting on whether the u channel should penalize more or v channel should penalize more?
or
it is each pixel and channel weight for activation larger than 0?

Will this weight make overall loss smaller?

and why the UV head needs Sigmoid?  only to normalize the activation to 0~1?  will this stabilize training and make it converge faster?
https://github.com/zengwang430521/DecoMR/blob/f96526ba9547d23cddd5931fa3fe75a49927e3f3/models/dense_cnn.py#L128

Thanks!

**Comment by zengwang430521** [comment]
Hi, when computing the loss between GT and estimated location map, we use different weights for different body parts. Parts far away from the torso are with higher weight. The gt_uv_weight is used to realize such weighted loss. It's used in the loss for location map but NOT the UV image. I'm sorry that the name is not so clear.

We use Sigmoid() to stabilize the training process. With UV values outside [0, 1], our feature warping function may cause some errors.

**Comment by wangzheallen** [comment]
Thanks for the answer.
I understand the weight (self.uv_weight) you are referring to which is in https://github.com/zengwang430521/DecoMR/blob/master/train/base_trainer.py#L226
and inside uv_loss
However, the gt_uv_weight is inside the dp_loss function https://github.com/zengwang430521/DecoMR/blob/master/train/base_trainer.py#L253
So I assume they are different.
I still cannot understand the
'gt_uv_weight = (gt_uv_shape.abs().max(dim=1, keepdim=True)[0] > 0).type(dtype)'
in https://github.com/zengwang430521/DecoMR/blob/master/train/base_trainer.py#L276

**Comment by zengwang430521** [comment]
High, gt_uv_weight is NOT used in the dp_loss function.  Actually the weight in dp_loss function is not a pixel-wise weight map. It's a sample-wise 1-D weight tensor. 

This weight vector is only used when we use the SPIN fitting results as GT. When using SPIN fitting for supervision, different samples are attached with different weight according to the fitting error of 2D joints. 

Such setting is not used when training with only data from H36M and UP-3D, because there GT meshes for these datasets.

**Comment by zengwang430521** [comment]
And for 'gt_uv_weight = (gt_uv_shape.abs().max(dim=1, keepdim=True)[0] > 0).type(dtype)'.

I'm sorry that it seems to be a mistake during the cleaning of the codes. The aim of gt_uv_weight is to adjust the weight for dp-uv channel according to the pixels with GT dp-uv. So that the dp-uv-loss will always be in a stable scale between different batches. Just like the loss for loss for smpl parameters. 

However, it seems that I wrote the wrong codes when cleaning the codes. Fortunately, this error did not caused serious performance drop. I will try to fix this error and retrain the model. When I get right results, I will update the codes to the master branch.

Before I update the codes, you can just keep the codes unchanged or simply remove **_gt_uv_weight_**  from the dp_loss function.

**Comment by wangzheallen** [comment]
> And for 'gt_uv_weight = (gt_uv_shape.abs().max(dim=1, keepdim=True)[0] > 0).type(dtype)'.
> 
> I'm sorry that it seems to be a mistake during the cleaning of the codes. The aim of gt_uv_weight is to adjust the weight for dp-uv channel according to the pixels with GT dp-uv. So that the dp-uv-loss will always be in a stable scale between different batches. Just like the loss for loss for smpl parameters.
> 
> However, it seems that I wrote the wrong codes when cleaning the codes. Fortunately, this error did not caused serious performance drop. I will try to fix this error and retrain the model. When I get right results, I will update the codes to the master branch.
> 
> Before I update the codes, you can just keep the codes unchanged or simply remove **_gt_uv_weight_** from the dp_loss function.

Thanks for looking back into the code! that clarification definitely helps! :-)
