### ISSUE TITLE
How to reconstruct mesh based on the vertex location

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#6]
May I ask how do you reconstruct SMPL parameters given the vertex location (location map) from your work? 
And what is the shape of the location map? (is that a 3 channel xyz denoting the camera coordinate in mm?)

**Comment by zengwang430521** [comment]
**SMPL parameters:**
Hi, the SMPL parameters are obtained with a light FC network and a simple optimization process.

We trained a light FC network which takes the vertex location as input and output the SMPL parameters. The loss is the L1 loss between the SMPL mesh vertex and the input vertex.  And the FC network is trained with the DecoMR framework fixed. 

The FC network aims to provide a rough estimation of the SMPL parameters, which is used as the initialization state of the following optimization process. The optimization process optimize the SMPL parameters to minimize the L1 loss between SMPL vertex and the vertex estimated by DecoMR. Since the initialization is usually good, we only need to optimize a few steps.

As this experiment is only included in the supplementary material, we did not provide the codes.

**Location map:**
The 3 channels xyz in the location map denote the coordinates in local coordinates ( the xy direction is aligned with the camera and the origin point is the pelvis of the person).
